# Generated by Django 4.2.7 on 2023-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=14)),
                ('laptop', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=20)),
                ('about', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=18)),
                ('re_password', models.CharField(max_length=18)),
                ('textarea', models.CharField(max_length=50)),
                ('RAM', models.IntegerField()),
                ('SSD', models.DecimalField(decimal_places=2, max_digits=3)),
                ('youtube_channel', models.BooleanField()),
            ],
        ),
    ]
