# Generated by Django 4.2.7 on 2023-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='youtube_channel',
            field=models.BooleanField(default=True),
        ),
    ]
